CFG_TEE_TA_LOG_LEVEL ?= 4
CPPFLAGS += -DCFG_TEE_TA_LOG_LEVEL=$(CFG_TEE_TA_LOG_LEVEL)

# The UUID for the Trusted Application
BINARY=abb6f4b6-8e33-4ad2-9805-e64f2c7cc70c



include $(TA_DEV_KIT_DIR)/mk/ta_dev_kit.mk
